version: "3.6"
services:
 sql-server-db:
  container_name: tab-db-server
  image: mcr.microsoft.com/mssql/server:2022-latest
  ports:
   - "1433:1433"
  environment:
   SA_PASSWORD: "tab"
   ACCEPT_EULA: "Y"
